version: '3.3'
services:
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_DATABASE: 'burp_collection'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '127.0.0.1:3306:3306'
    volumes:
      - db:/var/lib/mysql
# Names our volume
volumes:
  db:
